
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'es' | 'fr' | 'de' | 'it' | 'pt' | 'zh' | 'ja' | 'ko' | 'ar';

interface Translations {
  [key: string]: string;
}

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  languages: { code: Language; name: string; flag: string }[];
}

const translations: Record<Language, Translations> = {
  en: {
    'nav.home': 'Home',
    'nav.browse': 'Browse',
    'nav.list': 'List Item',
    'nav.signin': 'Sign In',
    'nav.signup': 'Sign Up',
    'nav.dashboard': 'Dashboard',
    'nav.messages': 'Messages',
    'nav.profile': 'Profile',
    'nav.logout': 'Sign Out',
    'hero.title': 'Rent Anything, Anytime',
    'hero.subtitle': 'Discover items and services in your neighborhood. Rent what you need, when you need it.',
    'hero.cta': 'Start Browsing',
    'hero.list': 'List Your Items',
    'search.placeholder': 'Search for items to rent...',
    'categories.title': 'Browse Categories',
    'featured.title': 'Featured Listings',
    'item.perDay': 'per day',
    'item.perHour': 'per hour',
    'item.perWeek': 'per week',
    'item.verified': 'Verified',
    'dashboard.listings': 'My Listings',
    'dashboard.bookings': 'My Bookings',
    'dashboard.wishlist': 'Wishlist',
    'dashboard.analytics': 'Analytics',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.price': 'Price',
    'common.location': 'Location',
    'common.category': 'Category',
    'common.rating': 'Rating',
    'common.reviews': 'Reviews',
    'booking.book': 'Book Now',
    'booking.dates': 'Select Dates',
    'booking.total': 'Total',
    'booking.confirm': 'Confirm Booking',
    'review.write': 'Write Review',
    'review.rating': 'Rating',
    'review.comment': 'Comment',
    'review.submit': 'Submit Review'
  },
  es: {
    'nav.home': 'Inicio',
    'nav.browse': 'Explorar',
    'nav.list': 'Publicar',
    'nav.signin': 'Iniciar Sesión',
    'nav.signup': 'Registrarse',
    'nav.dashboard': 'Panel',
    'nav.messages': 'Mensajes',
    'nav.profile': 'Perfil',
    'nav.logout': 'Cerrar Sesión',
    'hero.title': 'Alquila Cualquier Cosa, En Cualquier Momento',
    'hero.subtitle': 'Descubre artículos y servicios en tu vecindario. Alquila lo que necesites, cuando lo necesites.',
    'hero.cta': 'Comenzar a Explorar',
    'hero.list': 'Publicar Artículos',
    'search.placeholder': 'Buscar artículos para alquilar...',
    'categories.title': 'Explorar Categorías',
    'featured.title': 'Destacados',
    'item.perDay': 'por día',
    'item.perHour': 'por hora',
    'item.perWeek': 'por semana',
    'item.verified': 'Verificado',
    'dashboard.listings': 'Mis Publicaciones',
    'dashboard.bookings': 'Mis Reservas',
    'dashboard.wishlist': 'Lista de Deseos',
    'dashboard.analytics': 'Analíticas',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.save': 'Guardar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.view': 'Ver',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.sort': 'Ordenar',
    'common.price': 'Precio',
    'common.location': 'Ubicación',
    'common.category': 'Categoría',
    'common.rating': 'Calificación',
    'common.reviews': 'Reseñas',
    'booking.book': 'Reservar Ahora',
    'booking.dates': 'Seleccionar Fechas',
    'booking.total': 'Total',
    'booking.confirm': 'Confirmar Reserva',
    'review.write': 'Escribir Reseña',
    'review.rating': 'Calificación',
    'review.comment': 'Comentario',
    'review.submit': 'Enviar Reseña'
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.browse': 'Parcourir',
    'nav.list': 'Publier',
    'nav.signin': 'Se Connecter',
    'nav.signup': "S'inscrire",
    'nav.dashboard': 'Tableau de Bord',
    'nav.messages': 'Messages',
    'nav.profile': 'Profil',
    'nav.logout': 'Se Déconnecter',
    'hero.title': 'Louez Tout, À Tout Moment',
    'hero.subtitle': 'Découvrez des articles et services dans votre quartier. Louez ce dont vous avez besoin, quand vous en avez besoin.',
    'hero.cta': 'Commencer à Parcourir',
    'hero.list': 'Publier des Articles',
    'search.placeholder': 'Rechercher des articles à louer...',
    'categories.title': 'Parcourir les Catégories',
    'featured.title': 'Articles en Vedette',
    'item.perDay': 'par jour',
    'item.perHour': 'par heure',
    'item.perWeek': 'par semaine',
    'item.verified': 'Vérifié',
    'dashboard.listings': 'Mes Annonces',
    'dashboard.bookings': 'Mes Réservations',
    'dashboard.wishlist': 'Liste de Souhaits',
    'dashboard.analytics': 'Analytiques',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'common.save': 'Enregistrer',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.view': 'Voir',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.sort': 'Trier',
    'common.price': 'Prix',
    'common.location': 'Emplacement',
    'common.category': 'Catégorie',
    'common.rating': 'Notation',
    'common.reviews': 'Avis',
    'booking.book': 'Réserver Maintenant',
    'booking.dates': 'Sélectionner les Dates',
    'booking.total': 'Total',
    'booking.confirm': 'Confirmer la Réservation',
    'review.write': 'Écrire un Avis',
    'review.rating': 'Notation',
    'review.comment': 'Commentaire',
    'review.submit': 'Soumettre l\'Avis'
  },
  de: {
    'nav.home': 'Startseite',
    'nav.browse': 'Durchsuchen',
    'nav.list': 'Inserieren',
    'nav.signin': 'Anmelden',
    'nav.signup': 'Registrieren',
    'nav.dashboard': 'Dashboard',
    'nav.messages': 'Nachrichten',
    'nav.profile': 'Profil',
    'nav.logout': 'Abmelden',
    'hero.title': 'Miete Alles, Jederzeit',
    'hero.subtitle': 'Entdecke Gegenstände und Dienstleistungen in deiner Nachbarschaft. Miete was du brauchst, wann du es brauchst.',
    'hero.cta': 'Durchsuchen Starten',
    'hero.list': 'Artikel Inserieren',
    'search.placeholder': 'Nach Mietartikeln suchen...',
    'categories.title': 'Kategorien Durchsuchen',
    'featured.title': 'Empfohlene Angebote',
    'item.perDay': 'pro Tag',
    'item.perHour': 'pro Stunde',
    'item.perWeek': 'pro Woche',
    'item.verified': 'Verifiziert',
    'dashboard.listings': 'Meine Anzeigen',
    'dashboard.bookings': 'Meine Buchungen',
    'dashboard.wishlist': 'Wunschliste',
    'dashboard.analytics': 'Analytik',
    'common.loading': 'Laden...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.cancel': 'Abbrechen',
    'common.confirm': 'Bestätigen',
    'common.save': 'Speichern',
    'common.edit': 'Bearbeiten',
    'common.delete': 'Löschen',
    'common.view': 'Ansehen',
    'common.search': 'Suchen',
    'common.filter': 'Filtern',
    'common.sort': 'Sortieren',
    'common.price': 'Preis',
    'common.location': 'Standort',
    'common.category': 'Kategorie',
    'common.rating': 'Bewertung',
    'common.reviews': 'Bewertungen',
    'booking.book': 'Jetzt Buchen',
    'booking.dates': 'Daten Auswählen',
    'booking.total': 'Gesamt',
    'booking.confirm': 'Buchung Bestätigen',
    'review.write': 'Bewertung Schreiben',
    'review.rating': 'Bewertung',
    'review.comment': 'Kommentar',
    'review.submit': 'Bewertung Absenden'
  },
  it: {
    'nav.home': 'Home',
    'nav.browse': 'Sfoglia',
    'nav.list': 'Inserisci',
    'nav.signin': 'Accedi',
    'nav.signup': 'Registrati',
    'nav.dashboard': 'Dashboard',
    'nav.messages': 'Messaggi',
    'nav.profile': 'Profilo',
    'nav.logout': 'Disconnetti',
    'hero.title': 'Affitta Qualsiasi Cosa, In Qualsiasi Momento',
    'hero.subtitle': 'Scopri articoli e servizi nel tuo quartiere. Affitta quello che ti serve, quando ti serve.',
    'hero.cta': 'Inizia a Sfogliare',
    'hero.list': 'Inserisci Articoli',
    'search.placeholder': 'Cerca articoli da affittare...',
    'categories.title': 'Sfoglia Categorie',
    'featured.title': 'Articoli in Evidenza',
    'item.perDay': 'al giorno',
    'item.perHour': "all'ora",
    'item.perWeek': 'alla settimana',
    'item.verified': 'Verificato',
    'dashboard.listings': 'I Miei Annunci',
    'dashboard.bookings': 'Le Mie Prenotazioni',
    'dashboard.wishlist': 'Lista dei Desideri',
    'dashboard.analytics': 'Analitiche',
    'common.loading': 'Caricamento...',
    'common.error': 'Errore',
    'common.success': 'Successo',
    'common.cancel': 'Annulla',
    'common.confirm': 'Conferma',
    'common.save': 'Salva',
    'common.edit': 'Modifica',
    'common.delete': 'Elimina',
    'common.view': 'Visualizza',
    'common.search': 'Cerca',
    'common.filter': 'Filtra',
    'common.sort': 'Ordina',
    'common.price': 'Prezzo',
    'common.location': 'Posizione',
    'common.category': 'Categoria',
    'common.rating': 'Valutazione',
    'common.reviews': 'Recensioni',
    'booking.book': 'Prenota Ora',
    'booking.dates': 'Seleziona Date',
    'booking.total': 'Totale',
    'booking.confirm': 'Conferma Prenotazione',
    'review.write': 'Scrivi Recensione',
    'review.rating': 'Valutazione',
    'review.comment': 'Commento',
    'review.submit': 'Invia Recensione'
  },
  pt: {
    'nav.home': 'Início',
    'nav.browse': 'Explorar',
    'nav.list': 'Anunciar',
    'nav.signin': 'Entrar',
    'nav.signup': 'Registrar',
    'nav.dashboard': 'Painel',
    'nav.messages': 'Mensagens',
    'nav.profile': 'Perfil',
    'nav.logout': 'Sair',
    'hero.title': 'Alugue Qualquer Coisa, A Qualquer Hora',
    'hero.subtitle': 'Descubra itens e serviços no seu bairro. Alugue o que precisar, quando precisar.',
    'hero.cta': 'Começar a Explorar',
    'hero.list': 'Anunciar Itens',
    'search.placeholder': 'Buscar itens para alugar...',
    'categories.title': 'Explorar Categorias',
    'featured.title': 'Destaques',
    'item.perDay': 'por dia',
    'item.perHour': 'por hora',
    'item.perWeek': 'por semana',
    'item.verified': 'Verificado',
    'dashboard.listings': 'Meus Anúncios',
    'dashboard.bookings': 'Minhas Reservas',
    'dashboard.wishlist': 'Lista de Desejos',
    'dashboard.analytics': 'Analíticas',
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.save': 'Salvar',
    'common.edit': 'Editar',
    'common.delete': 'Excluir',
    'common.view': 'Ver',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.sort': 'Ordenar',
    'common.price': 'Preço',
    'common.location': 'Localização',
    'common.category': 'Categoria',
    'common.rating': 'Avaliação',
    'common.reviews': 'Avaliações',
    'booking.book': 'Reservar Agora',
    'booking.dates': 'Selecionar Datas',
    'booking.total': 'Total',
    'booking.confirm': 'Confirmar Reserva',
    'review.write': 'Escrever Avaliação',
    'review.rating': 'Avaliação',
    'review.comment': 'Comentário',
    'review.submit': 'Enviar Avaliação'
  },
  zh: {
    'nav.home': '首页',
    'nav.browse': '浏览',
    'nav.list': '发布',
    'nav.signin': '登录',
    'nav.signup': '注册',
    'nav.dashboard': '仪表板',
    'nav.messages': '消息',
    'nav.profile': '个人资料',
    'nav.logout': '登出',
    'hero.title': '随时租用任何物品',
    'hero.subtitle': '在您的社区发现物品和服务。随时租用您需要的物品。',
    'hero.cta': '开始浏览',
    'hero.list': '发布物品',
    'search.placeholder': '搜索租赁物品...',
    'categories.title': '浏览分类',
    'featured.title': '精选列表',
    'item.perDay': '每天',
    'item.perHour': '每小时',
    'item.perWeek': '每周',
    'item.verified': '已验证',
    'dashboard.listings': '我的列表',
    'dashboard.bookings': '我的预订',
    'dashboard.wishlist': '愿望清单',
    'dashboard.analytics': '分析',
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.save': '保存',
    'common.edit': '编辑',
    'common.delete': '删除',
    'common.view': '查看',
    'common.search': '搜索',
    'common.filter': '筛选',
    'common.sort': '排序',
    'common.price': '价格',
    'common.location': '位置',
    'common.category': '分类',
    'common.rating': '评分',
    'common.reviews': '评价',
    'booking.book': '立即预订',
    'booking.dates': '选择日期',
    'booking.total': '总计',
    'booking.confirm': '确认预订',
    'review.write': '写评价',
    'review.rating': '评分',
    'review.comment': '评论',
    'review.submit': '提交评价'
  },
  ja: {
    'nav.home': 'ホーム',
    'nav.browse': '閲覧',
    'nav.list': '掲載',
    'nav.signin': 'サインイン',
    'nav.signup': 'サインアップ',
    'nav.dashboard': 'ダッシュボード',
    'nav.messages': 'メッセージ',
    'nav.profile': 'プロフィール',
    'nav.logout': 'サインアウト',
    'hero.title': 'いつでも何でもレンタル',
    'hero.subtitle': 'お近くのアイテムやサービスを発見しましょう。必要な時に必要なものをレンタル。',
    'hero.cta': '閲覧開始',
    'hero.list': 'アイテム掲載',
    'search.placeholder': 'レンタルアイテムを検索...',
    'categories.title': 'カテゴリーを閲覧',
    'featured.title': '注目のリスティング',
    'item.perDay': '1日あたり',
    'item.perHour': '1時間あたり',
    'item.perWeek': '1週間あたり',
    'item.verified': '認証済み',
    'dashboard.listings': 'マイリスティング',
    'dashboard.bookings': 'マイ予約',
    'dashboard.wishlist': 'ウィッシュリスト',
    'dashboard.analytics': '分析',
    'common.loading': '読み込み中...',
    'common.error': 'エラー',
    'common.success': '成功',
    'common.cancel': 'キャンセル',
    'common.confirm': '確認',
    'common.save': '保存',
    'common.edit': '編集',
    'common.delete': '削除',
    'common.view': '表示',
    'common.search': '検索',
    'common.filter': 'フィルター',
    'common.sort': 'ソート',
    'common.price': '価格',
    'common.location': '場所',
    'common.category': 'カテゴリー',
    'common.rating': '評価',
    'common.reviews': 'レビュー',
    'booking.book': '今すぐ予約',
    'booking.dates': '日付選択',
    'booking.total': '合計',
    'booking.confirm': '予約確認',
    'review.write': 'レビューを書く',
    'review.rating': '評価',
    'review.comment': 'コメント',
    'review.submit': 'レビュー送信'
  },
  ko: {
    'nav.home': '홈',
    'nav.browse': '둘러보기',
    'nav.list': '등록',
    'nav.signin': '로그인',
    'nav.signup': '회원가입',
    'nav.dashboard': '대시보드',
    'nav.messages': '메시지',
    'nav.profile': '프로필',
    'nav.logout': '로그아웃',
    'hero.title': '언제든지 무엇이든 대여',
    'hero.subtitle': '주변의 물품과 서비스를 발견하세요. 필요할 때 필요한 것을 대여하세요.',
    'hero.cta': '둘러보기 시작',
    'hero.list': '물품 등록',
    'search.placeholder': '대여 물품 검색...',
    'categories.title': '카테고리 둘러보기',
    'featured.title': '추천 목록',
    'item.perDay': '일당',
    'item.perHour': '시간당',
    'item.perWeek': '주당',
    'item.verified': '인증됨',
    'dashboard.listings': '내 목록',
    'dashboard.bookings': '내 예약',
    'dashboard.wishlist': '위시리스트',
    'dashboard.analytics': '분석',
    'common.loading': '로딩 중...',
    'common.error': '오류',
    'common.success': '성공',
    'common.cancel': '취소',
    'common.confirm': '확인',
    'common.save': '저장',
    'common.edit': '편집',
    'common.delete': '삭제',
    'common.view': '보기',
    'common.search': '검색',
    'common.filter': '필터',
    'common.sort': '정렬',
    'common.price': '가격',
    'common.location': '위치',
    'common.category': '카테고리',
    'common.rating': '평점',
    'common.reviews': '리뷰',
    'booking.book': '지금 예약',
    'booking.dates': '날짜 선택',
    'booking.total': '총액',
    'booking.confirm': '예약 확인',
    'review.write': '리뷰 작성',
    'review.rating': '평점',
    'review.comment': '댓글',
    'review.submit': '리뷰 제출'
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.browse': 'تصفح',
    'nav.list': 'أدرج',
    'nav.signin': 'تسجيل الدخول',
    'nav.signup': 'اشتراك',
    'nav.dashboard': 'لوحة القيادة',
    'nav.messages': 'الرسائل',
    'nav.profile': 'الملف الشخصي',
    'nav.logout': 'تسجيل الخروج',
    'hero.title': 'استأجر أي شيء، في أي وقت',
    'hero.subtitle': 'اكتشف العناصر والخدمات في حيك. استأجر ما تحتاجه، عندما تحتاجه.',
    'hero.cta': 'ابدأ التصفح',
    'hero.list': 'أدرج عناصرك',
    'search.placeholder': 'ابحث عن عناصر للإيجار...',
    'categories.title': 'تصفح الفئات',
    'featured.title': 'القوائم المميزة',
    'item.perDay': 'يوميا',
    'item.perHour': 'ساعيا',
    'item.perWeek': 'أسبوعيا',
    'item.verified': 'موثق',
    'dashboard.listings': 'قوائمي',
    'dashboard.bookings': 'حجوزاتي',
    'dashboard.wishlist': 'قائمة الأمنيات',
    'dashboard.analytics': 'التحليلات',
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجح',
    'common.cancel': 'إلغاء',
    'common.confirm': 'تأكيد',
    'common.save': 'حفظ',
    'common.edit': 'تحرير',
    'common.delete': 'حذف',
    'common.view': 'عرض',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.sort': 'ترتيب',
    'common.price': 'السعر',
    'common.location': 'الموقع',
    'common.category': 'الفئة',
    'common.rating': 'التقييم',
    'common.reviews': 'المراجعات',
    'booking.book': 'احجز الآن',
    'booking.dates': 'اختر التواريخ',
    'booking.total': 'المجموع',
    'booking.confirm': 'تأكيد الحجز',
    'review.write': 'اكتب مراجعة',
    'review.rating': 'التقييم',
    'review.comment': 'تعليق',
    'review.submit': 'إرسال المراجعة'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  const languages = [
    { code: 'en' as Language, name: 'English', flag: '🇺🇸' },
    { code: 'es' as Language, name: 'Español', flag: '🇪🇸' },
    { code: 'fr' as Language, name: 'Français', flag: '🇫🇷' },
    { code: 'de' as Language, name: 'Deutsch', flag: '🇩🇪' },
    { code: 'it' as Language, name: 'Italiano', flag: '🇮🇹' },
    { code: 'pt' as Language, name: 'Português', flag: '🇵🇹' },
    { code: 'zh' as Language, name: '中文', flag: '🇨🇳' },
    { code: 'ja' as Language, name: '日本語', flag: '🇯🇵' },
    { code: 'ko' as Language, name: '한국어', flag: '🇰🇷' },
    { code: 'ar' as Language, name: 'العربية', flag: '🇸🇦' },
  ];

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
