// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfxtwwlvbxqtkzlzkzpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5meHR3d2x2YnhxdGt6bHprenBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3Mzc2NTQsImV4cCI6MjA2MzMxMzY1NH0.H7tU17IT9Q3du0_33GtiqEGKwv8Ugp0aVAKFWlhAh_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);